# KNN

###UTILIZANDO UN CONJUNTO DE DATOS DE PRUEBA DE SKLEARN

In [ ]:
from sklearn import datasets

iris = datasets.load_iris()
iris.feature_names
iris.target_names

print(iris.data)
print(iris.target)

from sklearn.model_selection import train_test_split 

x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target)
x_train
y_train
x_test
y_test

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=15)
knn.fit(x_train, y_train) 
knn.score(x_test, y_test) 

print(knn.predict(x_test))
print(y_test)
print(knn.predict(x_test[5:6][:4]))
print(y_test[5])

from sklearn.neighbors import RadiusNeighborsClassifier

knn_r = RadiusNeighborsClassifier(radius=0.7)

knn_r.fit(x_train, y_train) 
knn_r.score(x_test, y_test) 

print(knn_r.predict(x_test))
print(y_test)
knn_r.predict(x_test[2:3][:4])
y_test[2]

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

1

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

###UTILIZANDO UN CONJUNTO DE DATOS DE UCI
https://archive.ics.uci.edu/ml/index.php

In [ ]:
import pandas as pd
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/glass/glass.data')
print(df)
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,:10], df.iloc[:,10:11])
print(y_train)
print(y_test)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=15)  
knn.fit(x_train, y_train) 
knn.score(x_test, y_test)
print(x_test)
print(knn.predict(x_test))
print(y_test)


[2 2 2 2 2 2 2 2]
    2.30
22     2
23     2
25     2
1      1
5      1
28     2
19     2
13     2


In [ ]:
import numpy as np
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/lung-cancer/lung-cancer.data')
df
df.replace('?',0, inplace=True)
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,:55], df.iloc[:,55:56])
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train, y_train.values.ravel()) 
knn.score(x_test.astype('int'), y_test) 
print(knn.score(x_test, y_test) )
print(knn.predict(x_test))
print(y_test)

0.75
[2 2 2 2 2 2 2 2]
    2.30
22     2
23     2
25     2
1      1
5      1
28     2
19     2
13     2
